apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: helloworld-deployment
  name: helloworld-deployment
spec:
  ports:
  - port: 31001
    nodePort: 31001 
    protocol: TCP
    targetPort: web-port
  selector:
    app: helloworld-deployment
  type: NodePort
